<a href="https://colab.research.google.com/github/DhimanTarafdar/pytorch-nn-module/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn

Create a model class

In [6]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

create dummy dataset and call forward pass

In [7]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5305],
        [0.5214],
        [0.4092],
        [0.4003],
        [0.4410],
        [0.4376],
        [0.3677],
        [0.4617],
        [0.4910],
        [0.4455]], grad_fn=<SigmoidBackward0>)

In [8]:
model.linear.weight

Parameter containing:
tensor([[-0.3945, -0.1962, -0.0132, -0.3510, -0.3050]], requires_grad=True)

In [9]:
model.linear.bias

Parameter containing:
tensor([0.4056], requires_grad=True)

In [10]:
!pip install torchinfo

In [15]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Now create a nn with hidden layer (18 weights and 4 bias)



In [30]:
#again create model2
class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

In [38]:
features=torch.rand(10,5)
model2=Model2(features.shape[1])
model2(features)

tensor([[0.5934],
        [0.5578],
        [0.5751],
        [0.5850],
        [0.5852],
        [0.5767],
        [0.5617],
        [0.5680],
        [0.5886],
        [0.5626]], grad_fn=<SigmoidBackward0>)

In [39]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.2790,  0.2626, -0.0138, -0.3968,  0.0409],
        [ 0.2545,  0.1784,  0.4026,  0.0501, -0.3871],
        [-0.2908, -0.2101, -0.1047, -0.1182, -0.3817]], requires_grad=True)

In [40]:
model2.linear2.weight

Parameter containing:
tensor([[ 0.1892,  0.2438, -0.0606]], requires_grad=True)

In [41]:
model2.linear1.bias

Parameter containing:
tensor([0.3640, 0.0159, 0.1406], requires_grad=True)

In [42]:
model2.linear2.bias

Parameter containing:
tensor([0.1669], requires_grad=True)

In [43]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

effitient code for forward pass using sequential container

In [45]:
#again create model 3
class Model3(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self,features):
    out=self.network(features)
    return out

In [46]:
features=torch.rand(10,5)
model3=Model3(features.shape[1])
model3(features)

tensor([[0.6011],
        [0.6030],
        [0.6098],
        [0.5673],
        [0.5870],
        [0.5702],
        [0.5965],
        [0.5843],
        [0.5511],
        [0.5850]], grad_fn=<SigmoidBackward0>)

In [48]:
model3.network[0].weight

Parameter containing:
tensor([[-0.3131,  0.2963,  0.2036,  0.2523, -0.3371],
        [-0.0061, -0.1519,  0.0973,  0.0360,  0.4122],
        [ 0.0985, -0.4280,  0.0909,  0.2200, -0.0033]], requires_grad=True)

In [53]:
model3.network[2].weight

Parameter containing:
tensor([[ 0.3898,  0.3894, -0.5662]], requires_grad=True)